config/routes.rb
Dphaener::Application.routes.draw do
  resources :users

  resources :posts

  get "home/index"

  root 'home#index'

  get 'about' => 'home#about'
  get 'contact' => 'home#contact'
  get 'brewtools' => 'home#brewtools'
  get 'blog' => 'home#blog'
  get 'thrive' => 'home#thrive'
  get 'download' => 'home#download'

  

end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController

	def index
		@post = Post.last(1)
  end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

  def about
  end

  def contact
  end

  def brewtools
  end
  
  def blog
  end

  def thrive
  end

  def download
    case params[:file]
    when "Calculator"
      file_to_send = "/public/files/BJsCalculatorSetup.rar"
    end
    send_file file_to_send
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @post = Post.find(params[:id])
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    @post.creator = current_user.username

    if @post.creator.length == 0
      @post.creator = current_user.email
    end
    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    @post = Post.find(params[:id])
   
    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy
   
    redirect_to welcome_index_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :text, :creator)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end
	
	def create
	  user = User.authenticate(params[:credential_name], params[:password])
	  if user
	    session[:user_id] = user.id
	    redirect_to root_url
	  else
	    flash.now.alert = "Invalid email or password"
	    render "new"
	  end
	end
	
	def destroy
	  session[:user_id] = nil
	  redirect_to root_url
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    if @user.save
      user_log = User.authenticate(user_params[:email], user_params[:password])
      if user_log
        session[:user_id] = user_log.id
      end
      redirect_to root_url
    else
      render "new"
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    @user = User.find(params[:id])
   
    if @user.update(user_params)
      redirect_to @user
    else
      render 'edit'
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    
    redirect_to admin_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password, :username)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/index.html.erb
<h1>Administration Page</h1>
 
<table class="admin-table">
  <tr class="admin-header">
    <th>User Email</th>
    <th>Username</th>
    <th>Edit</th>
    <th>Delete</th>
  </tr>
  <% @users.each do |user| %>
    <tr class="user-info">
      <td><%= user.email %></td>
      <td><%= user.username %></td>
      <td><%= link_to "Edit", edit_user_path(user) %></td>
      <td><%= link_to "Delete", user_path(user), method: :delete, data: { confirm: 'Are you sure? This cannot be undone.' } %>
    </tr>
  <% end %>
</table>

app/views/home/about.html.erb
<div class="container">

  <%= render 'layouts/navbar' %>

  <!-- Jumbotron -->
  <div class="jumbotron">
    <h1 class="about-header">About Me</h1>
    <hr style="color:black;">
    <div class="left-portrait">
      <%= image_tag("Darin.JPG", class: "img-circle") %>
    </div>
    <div class="right-info">
      <p class="lead">Hey there, my name is Darin Haener. In a nutshell
        I'm a husband, dad, web developer, software developer, runner,
        cyclist, and small-time gardener. Not much else to say other
        than that without getting long-winded, so check out the rest
        of the site!</p>
    </div>
  </div>

  <!-- Site footer -->
  <div class="footer">
    <p>Darin Haener, 2013</p>
  </div>

</div> <!-- /container -->

app/views/home/blog.html.erb
<div class="container">
	<div class="jumbotron">
		<h3>This page is getting a facelift</h3>
		<h4>Please check back later</h4>
	</div>
</div>

app/views/home/brewtools.html.erb
<%= render 'layouts/navbar' %>

<div class="container">  
  <div class="jumbotron">
    <div class="left-portrait">
      <%= image_tag("beer-icon.png", class: "img-circle beer-pic") %>
    </div>
    <div class="right-info">
      <h1>Brewing Tool Projects</h1>
    </div>
    <hr style="color:black;">
    <span class="glyphicon glyphicon-download-alt glyphicon-brew pull-left"></span>
    <span class="pull-left"><%= link_to "BJ's Calulator Setup", "/files/BJsCalculatorSetup.rar" %></span>
    <ul class="brew-list clearBoth">
      <li class="brew-desc">
        <span class="glyphicon glyphicon-info-sign glyphicon-desc pull-left pull-down"></span>
        Unrar this puppy and run the setup file to install a 
        multi-faceted brewing calculator that contains a recipe database.<br />
        <span style="color:red">Warning: Database is Jet 4.0, so
          if you don't have that installed, it won't store any data, but
          the calculator will still work.</span>
      </li>
    </ul>
    <span class="glyphicon glyphicon-download-alt glyphicon-brew pull-left"></span>
    <span class="pull-left"><%= link_to "Darin's IBU Calculator", "/files/IBU Calculator - pH.xlsm" %></span>
      <ul class="brew-list clearBoth"><li class="brew-desc">
        <span class="glyphicon glyphicon-info-sign glyphicon-desc pull-left pull-down"></span>
        An IBU calculator that has many variables. It also includes
        my own utilization formula that I developed using a TON of real
        brewery data and laboratory analysis. It is in my opinion, the
        most accurate utilization formula out there.</li></ul>
    <span class="glyphicon glyphicon-download-alt glyphicon-brew pull-left"></span>
    <span class="pull-left"><%= link_to "Darin's Water Treatment Worksheet", "/files/Darins Water Treatment Worksheet.xlsx" %></span>
      <ul class="brew-list clearBoth"><li class="brew-desc">
        <span class="glyphicon glyphicon-info-sign glyphicon-desc pull-left pull-down"></span>
        A water treatment worksheet that allows you to fine tune your
        brewing water to match any of the world's famous brewing waters! 
        Hint: Kettle volume is expressed in gallons and all of the salt
        additions are in grams.</li></ul>
    <span class="glyphicon glyphicon-download-alt glyphicon-brew pull-left"></span>
    <span class="pull-left"><%= link_to "Darin's Wort Agar Worksheet", "/files/Wort Agar Worksheet.xlsx" %></span>
      <ul class="brew-list clearBoth"><li class="brew-desc">
        <span class="glyphicon glyphicon-info-sign glyphicon-desc pull-left pull-down"></span>
        A simple and scalable worksheet that allows you to quickly
        calculate the ingredients needed to make the perfect agar at the
        perfect gravity for growing yeast!</li></ul>
    <span class="glyphicon glyphicon-download-alt glyphicon-brew pull-left"></span>
    <span class="pull-left"><%= link_to "Orange Soda Worksheet", "/files/Orange Soda Worksheet.xls" %></span>
      <ul class="brew-list clearBoth"><li class="brew-desc">
        <span class="glyphicon glyphicon-info-sign glyphicon-desc pull-left pull-down"></span>
        A simple and scalable worksheet that allows you to quickly
        calculate needed ingredients for a batch of delicious orange cream
        soda! It also allows you to quickly and easily change the 
        proportions of the recipe (though I'm not sure why you would, it's
        delicious!)</li></ul>
    <span class="glyphicon glyphicon-download-alt glyphicon-brew pull-left"></span>
    <span class="pull-left"><%= link_to "Root Beer Worksheet", "/files/Root Beer Recipe.xlsx" %></span>
      <ul class="brew-list clearBoth"><li class="brew-desc">
        <span class="glyphicon glyphicon-info-sign glyphicon-desc pull-left pull-down"></span>
        Pretty much the same as above, but instead it's for, you 
        guessed it, Root Beer!</li></ul>
  </div>
</div>

<!-- Site footer -->
<div class="footer">
  <p>Darin Haener, 2013</p>
</div>

app/views/home/contact.html.erb
<div class="container">

  <%= render 'layouts/navbar' %>

  <!-- Jumbotron -->
  <div class="jumbotron">
    <h1 class="about-header">Contact Me</h1>
    <hr style="color:black;">
    <div class="left-portrait">
      <%= image_tag("Darin.JPG", class: "img-circle") %>
    </div>
    <div class="right-info">
      <p class="lead">If you'd like to contact me regarding my projects,
        my hobbies, or anything in general please feel free to email me
        at <a href="mailto:dphaener@gmail.com">dphaener@gmail.com</a>.</p>
    </div>
  </div>

  <!-- Site footer -->
  <div class="footer">
    <p>Darin Haener, 2013</p>
  </div>

</div> <!-- /container -->

app/views/home/index.html.erb
<div class="row">
  <div class="col-lg-4">
    <h2>dphBlog</h2>
    <p>My personal blog, which contains musings on open source software,
    politics, and other ramblings.....</p>
    <p><a class="btn btn-primary" href="/blog">Check it out! &raquo;</a></p>
  </div>
  <div class="col-lg-4">
    <h2>Thrive Nutrition and Fitness</h2>
    <p>A fitness and nutrition website that I started when I had high
      hopes of opening a company with the same name and ideals.  Of
      course, in my true style I only spent time creating the website
      because that's really what I love to do. Created with Drupal,
      I used mostly plugin modules other people had written, but the
      Nutrition Tracker portion (only available to logged in users) was
      written by yours truly....</p>
    <p><a class="btn btn-primary" href="/thrive">Check it out! &raquo;</a></p>
  </div>
  <div class="col-lg-4">
    <h2>Brewing Tools</h2>
    <p>Back in my former life, I was a professional brewer, and as I
      always do, found a way to work programming and complex spreadsheet
      development into my life and career. This is just a page of
      downloads that include spreadsheets, and software that I have
      written along the way....</p>
    <p><a class="btn btn-primary" href="/brewtools">Check it out! &raquo;</a></p>
  </div>
</div>

app/views/home/thrive.html.erb
<div class="container">
	<div class="jumbotron">
		<h3>This page is under construction</h3>
		<h4>Please check back later</h4>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dphaener</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="google-site-verification" content="RWCsJ7xFf6kHvTo_wjykhQC-ykr_Z5_Z5qOgjq_t-yU" />
</head>
<body>
  <div class="container">
    <div>
      <%= render 'shared/sidebar_nav' %>
    </div>

    <div class="main-container clearfix">
      <%= yield %>
    </div>

    <div class="footer clearfix">
      <p>Darin Haener, <%= Time.now.year %></p>
    </div>
  </div>

  <!-- Drip -->


  <script type="text/javascript">
    window.analytics=window.analytics||[],window.analytics.methods=["identify","group","track","page","pageview","alias","ready","on","once","off","trackLink","trackForm","trackClick","trackSubmit"],window.analytics.factory=function(t){return function(){var a=Array.prototype.slice.call(arguments);return a.unshift(t),window.analytics.push(a),window.analytics}};for(var i=0;i<window.analytics.methods.length;i++){var key=window.analytics.methods[i];window.analytics[key]=window.analytics.factory(key)}window.analytics.load=function(t){if(!document.getElementById("analytics-js")){var a=document.createElement("script");a.type="text/javascript",a.id="analytics-js",a.async=!0,a.src=("https:"===document.location.protocol?"https://":"http://")+"cdn.segment.io/analytics.js/v1/"+t+"/analytics.min.js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(a,n)}},window.analytics.SNIPPET_VERSION="2.0.9",
        window.analytics.load("twhe08p3qx");
    window.analytics.page();
  </script>
</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Listing posts</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/shared/_sidebar_nav.html.erb
<div class="sidebar well">
  <div class="left-portrait">
    <%= image_tag("Darin.JPG", class: "img-circle") %>
  </div>
  <div>
    <p>More stuff</p>
  </div>
</div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>